### PR TITLE
fix(setup-argo): do not require go binary

### PR DESCRIPTION
**Pull request by zerok**
Fixes https://github.com/grafana/shared-workflows/issues/482

### CODE REVIEW

**Comment by zerok** [comment]
The problem is that `setup-argo` currently assumes that a previous setup has already run `setup-go`. IMO we have two options here: Do the mapping ourselves from the `runner.os/arch` stuff, or install Go inside the action for the single purpose of doing the mapping for us. 

IMO, doing away with this "artificial" dependency is the better approach as either will fail if argo decided to change their package names but one does not require Go to be installed 🙂

**Comment by iainlane** [comment]
> assumes that a previous setup has already run `setup-go`.

Not quite - it assumes `go` is present on the runners, which is true for GitHub's images at least.

Have you got a concrete failure to point to?

**Comment by zerok** [comment]
> > assumes that a previous setup has already run `setup-go`.
> 
> Not quite - it assumes `go` is present when the step is run (no matter how it got there), which is true for GitHub's images at least.
> 
> Have you got a concrete failure to point to?

https://github.com/grafana/enghub/actions/runs/11701429721/job/32595152894 and probably the one listed in the original ticket.

**Comment by iainlane** [comment]
`go` is supposed to be installed on our internal runners but isn't due to a bug... but as far as I know the known blockers to us rolling out a fixed image are resolved now so we should be able to get back to a state where it is always there. @guicaulada is that right?

**Comment by zerok** [comment]
Working around this for now until the images are fixed 🙂

**Comment by iainlane** [comment]
FWIW the internal `arm64` runners should be fine

**Pull request closed without merging**
